/**
 * Git-hook integration content and layout (design of record:
 * "Distribution & git-hook integration").
 *
 * Modeled on Husky's engine/policy split. This module is pure — it owns the
 * *content* and *paths* of the two-tier hook layout; `governor init` (the CLI)
 * does the filesystem + git-config side effects. A future GUI frontend can
 * install the same layout from these same primitives.
 *
 * Layout:
 *   .governance/hooks/        (POLICY_DIR)  committed, repo-owned, editable
 *     pre-commit, commit-msg, …            ← shipped defaults, overridable
 *     _/                      (ENGINE_DIR)  generated, gitignored
 *       governor.sh                         ← the wrapper
 *       pre-commit, commit-msg, …           ← per-hook stubs git actually runs
 *
 * @module
 */

/** Value set as git `core.hooksPath`; git runs the stubs in the engine dir. */
export const HOOKS_PATH = ".governance/hooks/_";
/** The generated, gitignored engine directory (wrapper + per-hook stubs). */
export const ENGINE_DIR = ".governance/hooks/_";
/** The committed, repo-owned policy directory (editable default hooks). */
export const POLICY_DIR = ".governance/hooks";

/** The git lifecycle hooks Governor stubs by default. */
export const HOOK_NAMES: readonly string[] = ["pre-commit", "commit-msg"];

/** The git-config keys the signing mandate requires (Authority section). */
export const SIGNING_MANDATE_KEYS: readonly string[] = [
  "user.name",
  "user.email",
  "commit.gpgsign",
  "gpg.program",
  "user.signingkey",
];

/**
 * The wrapper script (`governor.sh`) sourced by every stub. Husky-shaped:
 * honor the `GOVERNOR=0` bypass, derive the hook name from the calling stub,
 * and run the sibling policy hook (the committed, editable file) if it exists,
 * propagating its exit status. POSIX sh for portability.
 */
export const WRAPPER = `#!/usr/bin/env sh
# Governor hook wrapper — generated; do not edit. Regenerated by \`governor init\`.
[ "$GOVERNOR" = "0" ] && exit 0

hook_name=$(basename "$0")
policy="$(dirname "$0")/../$hook_name"

[ -f "$policy" ] || exit 0
sh "$policy" "$@"
`;

/**
 * A per-hook stub placed in the engine dir; git invokes this. It just sources
 * the wrapper, which dispatches to the matching policy hook.
 */
export function stubScript(_hookName: string): string {
  return `#!/usr/bin/env sh
. "$(dirname -- "$0")/governor.sh"
`;
}

/** The shipped default policy hook body for a given git hook. */
export function defaultPolicyHook(hookName: string): string {
  switch (hookName) {
    case "pre-commit":
      return `#!/usr/bin/env sh
# Governor default pre-commit — reject the commit if the governance tree is invalid.
# Edit or remove this file to customize; add your own checks below.
governor check
`;
    case "commit-msg":
      return `#!/usr/bin/env sh
# Governor default commit-msg — review-boundary check (control 6): one staged
# WorkItem node per commit; stamps the Governor-WorkItem binding trailer. Edit to
# customize. (Approval stamping is out of scope; see ADR-0001.)
governor review-check "$1"
`;
    default:
      return `#!/usr/bin/env sh
# Governor ${hookName} hook — add your checks here.
exit 0
`;
  }
}

/**
 * Return the signing-mandate keys that are absent or unsatisfied in `config`.
 * `commit.gpgsign` must be present *and* truthy; the rest need only be present
 * and non-empty. An empty result means the mandate is satisfied.
 */
export function missingSigningKeys(config: Record<string, string>): string[] {
  return SIGNING_MANDATE_KEYS.filter((key) => {
    const value = config[key];
    if (value === undefined || value.trim() === "") return true;
    if (key === "commit.gpgsign") return value.trim().toLowerCase() !== "true";
    return false;
  });
}
